### ISSUE TITLE
Add modifier to enable/disable workflow and show it's current state

### ISSUE THREAD

**Issue by montemartin** [alfredapp/workflow-actions-workflow#1]
### Feature details

I have a number of workflows that I use very infrequently so I keep them disabled to avoid cluttering the UI. I'd love to be able to access and enable them directly through this workflow without the requirement of opening the settings page.

It would also be helpful to know whether each extension is active or not. One option to only show active workflows by default and use a different keyword a display inactive workflows. Another option would be to display them differently in the UI ( grayed out, or a different icon).

**Comment by vitorgalvao** [comment]
Thank you for the request. I mulled it over and ultimately decided not to do it for several reasons. Chief amongst them is that I want the workflow to remain blazing fast. Some people have hundreds of workflows installed, and because this presents the most recently viewed at the top, a cache cannot be used. Meaning that a full execution needs to happen every time.

Every check necessarily adds more computation (and thus delays) so I want to keep those to a minimum. Having modified images is immediately disqualified because it would require creating alternatives on demand for each disabled one. Then every single entry would need to have a check for their status and produce a different item which complicates the feature of having customisable modifiers (which is important since there are many options). Interface-wise, having items disappear on disabling would also require continuous reruns, though having an option to just not show disabled could work. Having a separate keyword for just disabled ones is something I don’t feel would be appropriate for this one.

Worth noting that I’m not opposed to those techniques and in fact use them in other workflows, such as [Library Sounds](https://alfred.app/workflows/vitor/library-sounds/) and [Virtual Machines](https://alfred.app/workflows/vitor/virtual-machines/), and it is precisely because I’ve done it before that I have a sense for how they could work in this workflow and feel they’re not entirely appropriate for its scope.

Note there are other workflows to search for workflows (at least two others) and other creators may have different goals. But for this one, and seeing it’s not a highly requested feature, passing at least for now. I’ll revisit if I come up with a satisfactory idea, I frequently keep these in mind and let them simmer for future releases.

Thank you again for the request. Have a great week.
